services:
  c_server:
    build: ./optimizacion_envios_c
    ports:
      - "3003:3000"
    networks:
      - app_network

  node_server:
    build: ./optimizacion_envios_node
    ports:
      - "3002:3000"
    networks:
      - app_network

  python_server:
    build: ./optimizacion_envios_python
    ports:
      - "3001:3000"
    networks:
      - app_network

  voting_server:
    build: ./voting_sync
    environment:
      - NODE_ENV=production
      - API_ENVIOS_C=http://c_server:3000/optimizacion_envios
      - API_ENVIOS_NODE=http://node_server:3000/optimizacion_envios
      - API_ENVIOS_PYTHON=http://python_server:3000/optimizacion_envios
    ports:
      - "3000:3000"
    networks:
      - app_network      

networks:
  app_network:
    driver: bridge
